services:
  parking:
    container_name: cvt_parking
    command: ./parking
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
    image: registry.infra.smartparking.kz/parking_cpp:v6.1.0-dev
    restart: always
    runtime: nvidia
    volumes:
      - ./config.json:/app/config.json
    logging:
      options:
        max-size: 50m
    networks:
      - parking-net
networks:
  parking-net:
    external: true
version: '2.1'
